spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "Jmj1234!!!"
    url: jdbc:mysql://localhost:3306/library
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true -> system out 으로 출력함
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: debug

server:
  error:
    include-exception: true